# Generated by Django 5.2.7 on 2025-11-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_clases'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notificaciones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
