# Generated by Django 5.2.8 on 2025-11-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_notificaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='notificaciones',
            new_name='notifications',
        ),
    ]
