# Generated by Django 5.2.8 on 2025-11-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='created_by',
            new_name='teacher',
        ),
    ]
