# Generated by Django 5.2.8 on 2025-12-31 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
    ]
