# Generated by Django 5.2.8 on 2025-12-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_create_clasemembership'),
    ]

    operations = [
    ]
