# Generated by Django 5.2.8 on 2025-12-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_rename_created_by_clase_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clases/'),
        ),
    ]
