# Generated by Django 6.0.1 on 2026-01-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0004_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clases/'),
        ),
    ]
