# Generated by Django 6.0.3 on 2026-04-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_announcementcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='clases.announcementcomment'),
        ),
    ]
