# Generated by Django 6.0.1 on 2026-01-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('sent', 'Enviado'), ('received', 'Recibido')], default='received', max_length=10),
        ),
    ]
